const QUESTIONS_DB = {
  temas: [
    {
      id: "epis",
      nombre: "EPIs – Equipos de Protección Individual",
      icono: "🦺",
      preguntas: [
        { id:"e1", p:"Entre otros, ¿a qué riesgos o situaciones se ven expuestos los bomberos?", ops:["Altas temperaturas, atmósferas contaminadas y riesgos físicos","Altas temperaturas, atmósferas explosivas y riesgos mecánicos","Altas temperaturas, atmósferas contaminadas y humos"], r:2 },
        { id:"e2", p:"Una de las responsabilidades del bombero para su trabajo a nivel de EPIs:", ops:["Entre otras, usarlo de forma correcta","Revisar y comprobar el estado de uso del EPI","Ninguna de las anteriores; se ocupa la empresa o entidad para la que trabaje"], r:0 },
        { id:"e3", p:"En cuanto a la elección de los EPIs en cada caso, señala la opción que NO se contempla:", ops:["Riesgos determinados, condiciones de trabajo y utilización","Zonas del cuerpo a proteger, condiciones de trabajo y utilización","Zonas del cuerpo a proteger, condiciones de trabajo y utilización, riesgos posibles"], r:0 },
        { id:"e4", p:"¿Qué se entiende por equipo de protección individual?", ops:["Cualquier equipo destinado a ser llevado o sujetado por el trabajador para que le proteja de uno o varios riesgos que puedan amenazar su seguridad o su salud, así como cualquier complemento o accesorio destinado a tal fin.","Todos los equipos destinados a ser llevados o sujetados por el trabajador para que le proteja de uno o varios riesgos, así como cualquier complemento o prenda destinado a tal fin.","Cualquier equipo destinado a ser llevado o sujetado por el trabajador para que le proteja de uno o varios riesgos que puedan amenazar su seguridad o su salud, así como cualquier complemento o prenda destinado a tal fin."], r:0 },
        { id:"e5", p:"De entre las diferentes prendas contempladas para evitar el contacto directo con agentes externos, NO está contemplado el tipo de riesgo:", ops:["Térmico y químico","Eléctrico","Derivados de cualquier intervención"], r:1 },
        { id:"e6", p:"¿Cuántos niveles de protección están reflejados?", ops:["2 niveles","4 niveles","Ninguna de las anteriores"], r:2 },
        { id:"e7", p:"Al NBQ le corresponde el nivel:", ops:["De menor protección","De mayor protección","Es nivel cero, también conocido como protección total"], r:1 },
        { id:"e8", p:"De los siguientes, uno NO está contemplado como equipo de intervención:", ops:["Casco, verdugo cubre pantalón, zapatos seguridad, guantes","Verdugo, chaquetón, guantes, casco","Chaquetón, verdugo cubre pantalón, guantes"], r:0 },
        { id:"e9", p:"Entre los componentes del verdugo se cuenta con:", ops:["El kevlar","Fibras sintéticas","Aramidas"], r:0 },
        { id:"e10", p:"El chaquetón contará con:", ops:["Bolsillos para herramientas","Bandas anti-destellos","Forro de Gore-Tex"], r:0 },
        { id:"e11", p:"Los guantes de intervención de bombero han de contar con:", ops:["Una homologación de uso","Una certificación para su uso","Una prueba de homologación para poder usarse"], r:1 },
        { id:"e12", p:"La clasificación de los Equipos de protección respiratoria se regula según norma:", ops:["UNE 133","UNE 134","EN 133"], r:2 },
        { id:"e13", p:"El tipo de retención que NO está contemplada dentro de los equipos filtrantes:", ops:["Retención mecánica","Mixtos","Retención fisicoquímica"], r:2 },
        { id:"e14", p:"Dentro de los equipos filtrantes, el denominado 'Filtro mixto + adaptador facial' se encuentra clasificado en:", ops:["EF Contra partículas","EF Contra partículas, gases y vapores","EF Contra gases y vapores"], r:1 },
        { id:"e15", p:"'Son aquellos que proporcionan aire para la respiración no perteneciente al medio ambiente en que se encuentra.' Esta definición corresponde a:", ops:["Equipos filtrantes","Equipos de protección individual respiratorios autónomos","Equipos respiratorios en general"], r:2 },
        { id:"e16", p:"La presión de llenado puede ser hasta de 300 bares en:", ops:["Equipos filtrantes comprimidos circuito abierto","Equipos de protección individual respiratorios autónomos","Equipos respiratorios aire comprimido de circuito abierto"], r:2 },
        { id:"e17", p:"Los equipos en circuito cerrado podrán ser:", ops:["Con uso de oxígeno y sin uso de oxígeno","Autónomos y semiautónomos","Con generación de oxígeno y sin generación de oxígeno"], r:2 },
        { id:"e18", p:"En caso de equipos autónomos de presión positiva, se mantiene en el interior de la máscara una ligera presión positiva ____________ durante la inhalación.", ops:["De unos pocos milibares","Unos pocos bares de presión","Normalmente con un bar de presión"], r:1 },
        { id:"e19", p:"El peso máximo para el equipo de aire comprimido será de:", ops:["18 kg más la máscara","20 kilos con la máscara","Con máscara y botellas llenas, tendrá un peso de 18 kg"], r:2 },
        { id:"e20", p:"El modelo de equipo de respiración usado por los bomberos de aeropuertos es:", ops:["ERA DB 69 MSA","BD 96 AUER","El Draguer DB 96"], r:1 },
        { id:"e21", p:"Los equipos respiratorios son tan solo dispositivos de protección contra gases:", ops:["Cierto, pero podrán ser usados en ambientes bacteriológicos","Falso, podrán ser usados a nivel subacuático","Las dos son falsas"], r:2 },
        { id:"e22", p:"¿A qué presión trabaja el reductor de presión de la botella?", ops:["7 bares de presión","58 bares de presión","11 bares de presión"], r:0 },
        { id:"e23", p:"El reductor de presión con sistema rápido es denominado como:", ops:["Quick Fill","Fill click","Clik fill"], r:0 },
        { id:"e24", p:"Las botellas de los equipos respiratorios podrán ser:", ops:["Tanto de acero como de aluminio","De acero y aleación carbono","De composite y de acero"], r:2 },
        { id:"e25", p:"Del equipo de respiración de los bomberos, el regulador será:", ops:["De depresión a demanda positiva","Presión positiva","De activación automática"], r:1 },
        { id:"e26", p:"El adaptador facial o máscara tiene como características (indica la que NO corresponde):", ops:["Estanqueidad, visibilidad","Visibilidad, comunicación visual","Visibilidad y comunicación oral"], r:1 },
        { id:"e27", p:"El color de las botellas de los equipos de respiración será:", ops:["El denominado por la norma DIN 3172","Por la legislación local","Podrá ser denominado por la norma DIN correspondiente o por legislación local"], r:2 },
        { id:"e28", p:"Los grifos en las botellas AUER de aire comprimido irán:", ops:["Algunos irán roscados","Todos irán roscados","Las dos son falsas; van introducidos mediante un sellado a presión"], r:0 },
        { id:"e29", p:"La conexión G 5/8 se corresponde con:", ops:["Según legislación local","Norma DIN 477","EN 144"], r:2 },
        { id:"e30", p:"La apertura de los grifos de las botellas se realizará en sentido:", ops:["A favor del sentido del reloj","En contra del sentido del reloj","Se abren dando al menos 2 vueltas indiferentemente del sentido"], r:1 },
        { id:"e31", p:"El llamado 'cierre deslizante' es:", ops:["Un mecanismo que evita los golpes en los grifos de las botellas","Un sistema que evita los golpes ariete al abrir el grifo y que salga el aire","Un mecanismo que impide que el grifo pueda apretarse en exceso solo al cerrarse"], r:2 },
        { id:"e32", p:"El denominado cierre deslizante se determina en el equipo:", ops:["BD 96","En todos los de la marca AUER","Ninguna es cierta"], r:0 },
        { id:"e33", p:"Las denominadas T en las botellas:", ops:["Permite conectar las botellas del tipo 6,8L/300 composite","No permite conectar las botellas del tipo 6,8L/300 ni composite ni aluminio","Permite conectar las botellas del tipo 6,8L/300 del tipo Aluminio"], r:0 },
        { id:"e34", p:"Los conectores para 115/200 son del tipo:", ops:["En forma de T","Rectos a la botella","Curvos"], r:0 },
        { id:"e35", p:"En la denominada prueba de estanqueidad se contempla:", ops:["El dispensador a demanda ha de estar interconectado","El interruptor a demanda ha de estar conectado a la máscara","Las dos son falsas"], r:2 },
        { id:"e36", p:"La presión mínima de las botellas será de:", ops:["270 bares para botellas de 400","180 para las botellas de 300","180 para botellas de 200"], r:2 },
        { id:"e37", p:"¿Qué tiempo determinaremos para comprobar que el cierre estanco del grifo de las botellas?", ops:["Será de 10 minutos","Será de 10 segundos","Será de 60 segundos"], r:2 },
        { id:"e38", p:"El avisador acústico de los equipos de las botellas es:", ops:["Solamente un avisador para tener una referencia","Una señal de alarma","Un sistema que se programa para que suene cuando determinemos"], r:1 },
        { id:"e39", p:"¿Cómo nos colocaremos el equipo de respiración?", ops:["Conectando el regulador a la máscara","Con la rosca hacia arriba del equipo para acceder bien","Conectaremos el regulador a la máscara cuando nos dispongamos a entrar"], r:0 },
        { id:"e40", p:"¿Qué pasa cuando suena el pitido del equipo?", ops:["Abriremos más las botellas; necesitamos más aire","Regresaremos al aire limpio","Cambiaremos la botella allí mismo aguantando unos instantes la respiración"], r:1 },
        { id:"e41", p:"¿Qué pautas seguiremos para quitarnos el equipo de aire respirable?", ops:["Lo primero será quitarse la máscara","Desconectaremos el adaptador facial","Dejaremos salir el aire; ese aire ya no es bueno para volver a usarse"], r:0 },
        { id:"e42", p:"Los atalajes del equipo ERA se aflojan:", ops:["Bajando el dedo pulgar cerradura metálica","Levantando el pulgar la cerradura de metal","Subiendo el dedo índice de los tensores"], r:1 },
        { id:"e43", p:"En cuanto a la carga de los ERA, indica la que NO corresponde:", ops:["Se han de cargar con aire respirable","Se ha de dejar enfriar antes de usarlas; sabremos su presión correcta","Se podrán cargar con cualquier aire ambiente"], r:2 },
        { id:"e44", p:"Se deben cerrar los grifos inmediatamente después de ser usados:", ops:["Verdadero","Falso","Se debe dejar abierto y desconectar la máscara"], r:0 },
        { id:"e45", p:"Las bocas de los grifos serán taponadas:", ops:["Inmediatamente después de recargarlas","Solamente en el caso de recargar","Solo en el caso de desconectar las botellas del ERA"], r:2 },
        // REPASO EPIs
        { id:"er1", p:"En cuanto a los equipos de protección personal, indica la que NO corresponde:", ops:["Siendo bien usados, garantizarán totalmente la seguridad de los bomberos","Ningún equipo de protección personal garantizará totalmente la seguridad","Disminuyen notablemente el riesgo de sufrir lesiones"], r:0 },
        { id:"er2", p:"Las radiaciones a las que pueden estar sometidos los bomberos son:", ops:["Alfa y beta","Exclusivamente las generadas por las llamas y calor","Alfa, beta y omega"], r:0 },
        { id:"er3", p:"El equipo de nivel 1 incluye entre otros:", ops:["Equipo de intervención completo más el ERA","Equipo de intervención y traje anti-salpicaduras","Equipo de intervención y NBQ"], r:0 },
        { id:"er4", p:"El chaquetón de bomberos contará con:", ops:["Muñequeras","Alzacuellos","Capa para cubrirnos"], r:0 },
        { id:"er5", p:"Los zapatos que disponen los bomberos se podrán usar en:", ops:["Trabajos de intervención","Trabajos de parque","Solo para representación"], r:1 },
        { id:"er6", p:"Indica la correcta:", ops:["Los equipos filtrantes son independientes del medio ambiente","Los equipos respiratorios son dependientes del medio ambiente","Las dos son falsas"], r:2 },
        { id:"er7", p:"Indica la correcta: los equipos respiratorios semiautónomos podrán ser:", ops:["Circuito abierto","Equipos de aire fresco","Circuito cerrado y circuito abierto"], r:2 },
        { id:"er8", p:"¿En qué tipo de equipos la presión máxima de trabajo será de 10 bares?", ops:["En los de línea de aire respirable","En los de línea de aire comprimido","En los de manguera de asistencia a presión"], r:1 },
        { id:"er9", p:"¿Qué tipo de equipos elimina solamente el CO2 procedente de la respiración?", ops:["Son de circuito abierto sin generación de oxígeno","Circuito cerrado sin generación de oxígeno","Circuito cerrado con generación de oxígeno"], r:1 },
        { id:"er10", p:"Señala la opción correcta de los equipos de circuito abierto:", ops:["En los equipos de circuito abierto de aire comprimido el contenido de agua debe ser inferior a 20 mg/m³ a 300 bares o 45 mg/m³ a 200 bares","En los equipos de circuito abierto de aire comprimido el contenido de agua debe ser inferior a 30 mg/m³ a 300 bares o 50 mg/m³ a 200 bares","En los equipos de circuito abierto de aire comprimido el contenido de agua debe ser inferior a 30 mg/m³ a 300 bares o 60 mg/m³ a 200 bares"], r:1 },
        { id:"er11", p:"El diseño del equipo NO debe cumplir de los siguientes requerimientos:", ops:["Máxima penetración permitida de la máscara 0,05%","Protección ocular y robustez mecánica","Campo de acción de la máscara y penetración de 0,5%"], r:2 },
        { id:"er12", p:"¿Cuál es la definición correcta?", ops:["El equipo BD 86 de AUER es un aparato de protección respiratoria de circuito abierto, independiente del aire ambiente.","El equipo BD 96 de AUER es un aparato autónomo de protección respiratoria de circuito abierto, independiente del aire ambiente.","El equipo BS 96 de AUER es un aparato independiente de protección respiratoria de circuito abierto, independiente del aire ambiente."], r:1 },
        { id:"er13", p:"Indica la opción que corresponda sobre el aire exhalado:", ops:["El aire exhalado se libera a través de la válvula de exhalación del adaptador facial directamente a la atmósfera ambiente.","El aire inhalado se libera a través de la válvula de entrada del adaptador facial directamente a la atmósfera ambiente.","El aire exhalado se libera a través de la válvula de exhalación del regulador directamente a la atmósfera ambiente."], r:0 },
        { id:"er14", p:"Los atalajes del equipo ERA contarán:", ops:["Con cierre de seguridad","Fibra de aramida/lana","Serán autoextinguibles"], r:2 },
        { id:"er15", p:"En cuanto al equipo ERA podemos decir que:", ops:["Su reductor de presión será de latón del tipo 500 E","El regulador de presión será de tipo E 500","Las dos son falsas"], r:2 },
        { id:"er16", p:"El avisador acústico del equipo ERA será ajustado para avisar a:", ops:["Cuando la presión de la botella será de 58 bar aprox.","Cuando la presión del equipo sea de 85 bar aprox.","Avisará a lo que nosotros lo programemos"], r:0 },
        { id:"er17", p:"El avisador acústico del equipo ERA:", ops:["Se dispone en una línea independiente","Está integrado en la misma línea de presión del equipo","El tipo S está integrado dentro de la línea de presión"], r:0 },
        { id:"er18", p:"Los equipos ERA, en el caso del reductor de presión:", ops:["El tipo 500 E Z lleva en la parte derecha del cinturón una segunda conexión","Todos los equipos 500 E tipo S llevan una línea de segunda conexión","Todos los equipos se les puede acoplar una segunda línea de conexión"], r:0 },
        { id:"er19", p:"De las siguientes, NO será necesario para el regulador automático:", ops:["Manejable ergonómico operable con guantes incluso","Activación automática al ponerse la máscara","Desactivación automática al quitarse la máscara"], r:1 },
        { id:"er20", p:"En cuanto a las botellas de aire comprimido de los ERAs, NO corresponde:", ops:["El equipo debe ser conforme a normativa","El hielo que se forme en grifo y otros elementos afectará a su funcionamiento","El aire dependerá de la humedad y temperatura de la atmósfera ambiente"], r:1 },
        { id:"er21", p:"Las botellas estándar podrán disponer:", ops:["De un dispositivo adicional de apertura","Deben abrirse dándoles por lo menos un giro completo","El mando lleva siempre un protector de goma contra impactos"], r:2 },
        { id:"er22", p:"Entre las precauciones de uso, indica la correcta:", ops:["Las botellas que no se usen podrán estar descargadas","Las botellas siempre deben estar bien protegidas de golpes en su uso y transporte","Las botellas no se han de coger por el cuello de la botella (grifo), sí por el mando"], r:1 },
      ]
    },
    {
      id: "aeronaves",
      nombre: "Aeronaves",
      icono: "✈️",
      preguntas: [
        { id:"a1", p:"El avión se considera el transporte:", ops:["Más rápido","Más seguro","El tren le supera en seguridad"], r:1 },
        { id:"a2", p:"La afirmación de seguridad está referida en torno al:", ops:["Número de pasajeros que lo usan","Número de víctimas por cantidad de pasajeros que lo usan","Número de accidentes por población"], r:1 },
        { id:"a3", p:"De los datos se desprende que el uso del automóvil tiene:", ops:["Una tasa 20 veces mayor que el avión","Una tasa 20 veces menor que el avión","Aproximadamente igual que el avión, tren o incluso motos"], r:0 },
        { id:"a4", p:"En 1970 se produjeron:", ops:["Aproximadamente 5 millones de despegues en los aeropuertos","Exactamente unos 6 millones de despegues","Es un dato que no podemos saber con exactitud, pero unos 5 millones"], r:1 },
        { id:"a5", p:"Durante 1972 se produjeron 2556 víctimas en ámbito aéreo:", ops:["Verdadero","Falso","2526 exactamente"], r:0 },
        { id:"a6", p:"¿Cuántos accidentes dice el temario de AENA que se dieron en el año 2000?", ops:["31","13","32"], r:2 },
        { id:"a7", p:"De los datos se deduce que la siniestralidad:", ops:["Desgraciadamente se mantiene","Peor aún... aumenta","Disminuye"], r:1 },
        { id:"a8", p:"De la evolución estadística, los datos indican que la siniestralidad:", ops:["Se mantiene","Disminuye","Aumenta"], r:2 },
        { id:"a9", p:"Los sucesos aeronáuticos con heridos y daños materiales son considerados:", ops:["Accidentes","Accidentes leves","Incidentes"], r:2 },
        { id:"a10", p:"Los accidentes cuando ocurren se suelen deber a:", ops:["A una sola causa","Varias causas encadenadas","A la suma de varios factores"], r:2 },
        { id:"a11", p:"Dentro de los fallos cometidos en los accidentes aéreos:", ops:["Fallos humanos","Los fallos humanos representan solo 1/3 parte","Ninguna de las anteriores"], r:2 },
        { id:"a12", p:"Las aves en los aeropuertos son consideradas como:", ops:["Una amenaza a los despegues","Están protegidas por ley","Se consideran una incidencia"], r:2 },
        { id:"a13", p:"¿En cuál de estas fases del avión tiene menor tasa de accidentes?", ops:["Taxi","Crucero","Aparcado"], r:0 },
        { id:"a14", p:"La fase de aproximación al aeropuerto es la más:", ops:["Peligrosa","Importante","Tranquila; el avión apenas se mueve"], r:0 },
        { id:"a15", p:"Los aviones van por un camino establecido en el aire:", ops:["Verdadero","Falso","Un camino sobre ciudades, mares, montañas"], r:1 },
        { id:"a16", p:"Las consecuencias de los accidentes aéreos son:", ops:["Muy concretas: la compañía pierde dinero, prestigio y atención psicológica a los familiares","Son muy variadas","Ninguna de las anteriores"], r:1 },
        { id:"a17", p:"¿Cuántos componentes conforman la estructura de una aeronave?", ops:["El fuselaje se designa así; los incluye ya","4 componentes","5 componentes y el tren de aterrizaje aparte"], r:1 },
        { id:"a18", p:"El suelo de un fuselaje está compuesto entre otros por:", ops:["Vigas","Vigas y cuadernas","Cuadernas, vigas y larguerillos"], r:2 },
        { id:"a19", p:"Tiene forma de aro:", ops:["La barriga del avión","Los larguerillos","Las cuadernas"], r:2 },
        { id:"a20", p:"El avión necesita despresurizarse para volar:", ops:["Sí; así pesa menos el aire que lleva y sube","No, falso","Sí; necesita despresurizarse para que a los pasajeros no les estallen los oídos al subir"], r:1 },
        { id:"a21", p:"El tiempo sobre el total del vuelo es superior en la fase de taxi que en la de aterrizaje:", ops:["Sí, sin duda; tenemos que llegar al aeropuerto","No, falso; es igual","Es superior en la de aterrizaje"], r:1 },
        { id:"a22", p:"El estudio de porcentajes de accidentes sufridos por el total de la flota mundial:", ops:["Dicho estudio se realizó en estos últimos 30 años","Comenzó en 1959 y finalizó en 1995","Comenzó en 1059 hasta hoy día"], r:1 },
        { id:"a23", p:"La suma de la aproximación final y aterrizaje son casi:", ops:["El 40% del total empleado","La mitad del total empleado","Son apenas un 22%"], r:1 },
        { id:"a24", p:"Del temario se desprende que el avión es un medio de transporte:", ops:["Fiable","Fiable y rápido","El más seguro"], r:2 },
        { id:"a25", p:"¿Cuántos despegues se realizaron en 1972?", ops:["Más de 6 millones","Entre 7 y 8 millones","Exactamente 6 millones"], r:0 },
        { id:"a26", p:"Todos los accidentes aéreos tienen:", ops:["Una causa","Más de una causa y varios factores desencadenantes","Un factor que los desencadena y varios factores"], r:2 },
        { id:"a27", p:"Los informes que disponemos de accidentes y sus causas, ¿los realiza?", ops:["AENA","Una agencia de investigación","Los hace el ministerio de fomento en su delegación de agencias estatales de seguridad aérea"], r:1 },
        { id:"a28", p:"La proporción de causas atribuidas a condiciones atmosféricas en los accidentes aéreos:", ops:["Pueden llegar a la tercera parte","Son las dos terceras partes","Son el resto, de las humanas sobre el total"], r:2 },
        { id:"a29", p:"Las aves son un factor más en las colisiones de aviones:", ops:["Sí, es un factor","Más que un factor, es un problema que condiciona los despegues","Condiciona mucho la zona donde esté situado el aeropuerto"], r:0 },
        { id:"a30", p:"A la hora de tener en cuenta los accidentes, se tienen en cuenta a nivel estadístico:", ops:["Los aeropuertos","Los aeropuertos y sus proximidades","Los aeropuertos, la terminal, la pista, la ruta que sigue el avión"], r:1 },
        { id:"a31", p:"La mayor zona de incidencia de accidentes según el gráfico de la figura 15.17:", ops:["Se da casi al final de la gráfica","Se da en la zona de 2/3 del final de la gráfica","Se da en el último tercio de la longitud de la pista"], r:2 },
        { id:"a32", p:"La figura 15.17, acceso a la zona de accidentes:", ops:["Cuenta con una escala en metros","Cuenta con una escala en pies","Las dos anteriores son correctas"], r:2 },
        { id:"a33", p:"En general se considera que el avión es:", ops:["Un aparato muy resistente a los impactos","Poco resistente a los impactos","Muy resistente y fiable"], r:1 },
        { id:"a34", p:"Una aeronave presenta unos componentes, entre los cuales:", ops:["Fuselaje, cola, alas, tren de aterrizaje","Casco, cola, tren de aterrizaje y alas","Empenaje de cola, tren de aterrizaje y fuselaje"], r:2 },
        { id:"a35", p:"De las fotos de las secciones de avión, se desprende o interpretamos:", ops:["Que la zona de carga se sitúa encima de los pasajeros","La zona de pasaje está arriba y la de carga está situada debajo","No; la zona de pasaje está a todo el largo del avión y encima el portaequipajes de mano"], r:1 },
        { id:"a36", p:"El diámetro de la sección del avión:", ops:["Es el mismo en toda su longitud","Suele ser el mismo","No puede variar ni un milímetro, sino se descompensa y no vuela"], r:1 },
        { id:"a37", p:"El fuselaje se construye por:", ops:["Tramos","Cuadernas y vigas","Secciones"], r:2 },
        { id:"a38", p:"El cockpit es:", ops:["Lugar donde está la tripulación","Donde se calienta café, se tienen los office de alimentos, el catering","Donde se realizan las tareas de pilotaje y de operación del avión"], r:2 },
        { id:"a39", p:"Las TCA e ILS están situadas:", ops:["En el techo del avión","En la cabina","Debajo de los galleys"], r:1 },
        { id:"a40", p:"Los galleys son:", ops:["Los baños o servicios","Dependencias donde está la cocina del avión","Unos almacenes de carga"], r:1 },
        { id:"a41", p:"Los galleys llevan:", ops:["Extintores","Sistema automático de extinción","Ninguna de las anteriores"], r:2 },
        { id:"a42", p:"Para que un avión sea considerado wide body:", ops:["Ha de tener al menos más de un pasillo","Ha de tener más de 4,5 metros de ancho de fuselaje (diámetro)","Ha de tener varios asientos por filas"], r:1 },
        { id:"a43", p:"Los aviones según su ancho se dividen en varios tipos:", ops:["Solo en tres tipos: ancho, medio y big body","Dos tipos únicamente","Fuselaje estrecho y narrow body únicamente"], r:1 },
        { id:"a44", p:"Los aviones considerados de fuselaje ancho:", ops:["Tienen más de seis asientos por fila","Siempre disponen de dos pasillos","Las dos son correctas"], r:0 },
        { id:"a45", p:"Los lavabos están colocados:", ops:["Dentro de la cabina de tripulación","Fuera de la cabina","En la zona destinada al pasaje"], r:2 },
        { id:"a46", p:"Los baños llevan cortinas:", ops:["Correcto","No, llevan puertas abatibles","Ninguna de las anteriores"], r:2 },
        { id:"a47", p:"Las cortinas y las puertas de los lavabos han de permanecer abiertas en las maniobras de despegue:", ops:["Sí, sin duda","Los lavabos no","Solo los lavabos"], r:1 },
        { id:"a48", p:"Las bodegas de carga están situadas debajo del fuselaje:", ops:["Sí; su función es el transporte de equipajes y carga","Siempre la carga está metida en contenedores especiales","Pueden estar presurizadas"], r:2 },
        { id:"a49", p:"Las puertas de acceso al avión para personal de maletas están situadas:", ops:["En la zona izquierda","En la parte izquierda de delante junto a la cabina","Parte atrás derecha"], r:2 },
        { id:"a50", p:"Los accionamientos de las puertas de acceso a bodegas suelen realizarse manualmente por seguridad:", ops:["Podrán ser eléctricas también","Siempre manual para asegurar su cierre y apertura","Son automáticas controladas por los pilotos"], r:0 },
        { id:"a51", p:"¿Por qué lado del avión se realiza en una emergencia la evacuación del pasaje y de la tripulación?", ops:["Por la zona izquierda siempre","Ambos lados","Por la zona derecha preferiblemente"], r:1 },
        { id:"a52", p:"Las puertas se abren:", ops:["De fuera a adentro","De dentro a fuera","De lado; son corredizas"], r:1 },
        { id:"a53", p:"Los accionamientos de las puertas pueden ser:", ops:["Eléctricos o neumáticos","Eléctricos y manuales","Neumáticos y manuales"], r:1 },
        { id:"a54", p:"Las puertas están normalizadas en cuanto a peso, altura y dimensiones:", ops:["No; son especiales según lo que el fuselaje permita","Están normalizadas","Están normalizadas según modelo y fabricante, pues todos los aviones son iguales"], r:1 },
        { id:"a55", p:"Las puertas se cierran:", ops:["De forma de dentro hacia fuera","Como las puertas de los barcos","De forma de fuera a dentro, asegurando su hermetismo"], r:0 },
        { id:"a56", p:"Los mecanismos de acción de las puertas solo pueden ser accionados por la tripulación:", ops:["Correcto","Por seguridad por la tripulación solo en caso de emergencia","Pueden accionarlos y deben cualquiera"], r:2 },
        { id:"a57", p:"Las alas de un avión:", ops:["Son los elementos que le permiten volar","Son los responsables de que tenga sustentación y estabilidad","Ninguna de las anteriores"], r:0 },
        { id:"a58", p:"Los planos de un avión:", ops:["Normalmente están en la cabina para poder consultarlos en caso de emergencia","Determinan un cajón hueco","Los planos suelen estar en la zona de pasajeros para poder guiarse en caso de emergencia"], r:1 },
        { id:"a59", p:"Las alas:", ops:["Son independientes al resto del avión","Se construyen a la misma vez que el fuselaje","Se unen al fuselaje"], r:2 },
        { id:"a60", p:"La forma de las alas varía en función:", ops:["Del ingeniero que las diseña y fabrica","Depende del fabricante: americanos, rusos, europeos","De los requerimientos aerodinámicos"], r:2 },
        { id:"a61", p:"Los aviones más lentos:", ops:["Tienen más alas","Tienen solo dos alas","Tienen menos alas"], r:1 },
        { id:"a62", p:"Los planos tienen una forma de flecha:", ops:["Flecha invertida","Flecha inclinada a fuera","Flecha inclinada hacia atrás"], r:2 },
        { id:"a63", p:"La superficie alar consiste:", ops:["En la suma de todas las alas","En la suma de la superficie de un ala multiplicada por el número de ellas","En la suma del cuadrado de las alas"], r:1 },
        { id:"a64", p:"La razón de que las alas terminen en punta en su extremo es:", ops:["Por una cuestión de diseño","Por una cuestión de fabricación","Por una cuestión de reparto de fuerzas"], r:2 },
        { id:"a65", p:"El extradós del ala de un avión está situado:", ops:["En su parte externa","En su parte superior","Ninguna de las anteriores"], r:1 },
        { id:"a66", p:"La parte que primero tiene contacto con el aire al volar:", ops:["Es el borde de fuga","Es el ala completa a la vez","El borde de ataque"], r:2 },
        { id:"a67", p:"Podríamos definir el espesor de un ala como:", ops:["La distancia que va desde borde de ataque al de salida","La distancia entre el borde de salida y el ataque","La distancia entre el extradós y el intradós"], r:2 },
        { id:"a68", p:"Los flaps nos permiten:", ops:["Aumentar las alas","Solo una posición afuera","Darle más envergadura al avión"], r:0 },
        { id:"a69", p:"El término 'flaps up' significa dentro del contexto de aeronáutica:", ops:["Arriba los flaps","Levantados los flaps","Retraídos"], r:2 },
        { id:"a70", p:"Los slats:", ops:["Aumentan la superficie alar","Aumentan la curvatura del avión","Aumentan la curvatura del avión y la superficie"], r:0 },
        { id:"a71", p:"En el caso de los slats:", ops:["Generan mayor velocidad al paso del aire","Se despliegan delante y arriba del ala","Ayudan a que el avión suba mejor"], r:0 },
        { id:"a72", p:"El accionamiento de los slats y los flaps:", ops:["Es independiente","Es coordinado","Es simultáneo"], r:0 },
        { id:"a73", p:"El concepto 'flap lowered':", ops:["Es incorrecto; lo correcto es slat y flap extended","Significa que está extendido solo el flap","Significa que está dentro el flap del ala"], r:1 },
        { id:"a74", p:"Los spoilers están situados:", ops:["Dentro del ala","En la superficie del ala","Sirven para ayudar al flujo como los F1"], r:1 },
        { id:"a75", p:"Los spoilers normalmente:", ops:["Están levantados sobre el ala","Están en la punta del ala para ayudar al flujo","Están sin accionar"], r:2 },
        { id:"a76", p:"Los spoilers son elementos ubicados en el fuselaje del ala:", ops:["Correcto","Son unas superficies móviles","Ayudan a subir el avión"], r:1 },
        { id:"a77", p:"Los spoilers:", ops:["Trabajan en tierra","Ayudan a girar","Las dos anteriores son correctas"], r:2 },
        { id:"a78", p:"¿Qué se genera en el ala de un avión, según el temario de AENA?", ops:["Se generan depresiones","Aumento de presiones","Diferencias de presiones"], r:2 },
        { id:"a79", p:"Estas presiones que se generan en las alas de los aviones:", ops:["Permiten volar más rápido al avión","Permiten sustentar al avión mejor","Aumentan la resistencia al avión"], r:1 },
        { id:"a80", p:"Los winglets:", ops:["Están sobre el fuselaje","Están en la punta del ala para ayudar al flujo","Eliminan en parte el efecto de remolinos"], r:2 },
        { id:"a81", p:"Para ayudar al efecto de presiones producidas en las alas:", ops:["Se montan unos spoilers","Se colocan 2 winglets por ala, uno encima y otro debajo","Se coloca uno por ala, o sea 2 winglets en total para todo el avión"], r:1 },
        { id:"a82", p:"Las causas para montar los winglets son:", ops:["Una: el paso del aire por el ala","Una: la presión que se genera en el ala","Las dos anteriores"], r:2 },
        { id:"a83", p:"El empenaje de cola está conformado básicamente por:", ops:["Un estabilizador vertical y los timones","Dos superficies: horizontal y vertical","Ninguna de las anteriores"], r:1 },
        { id:"a84", p:"Los números 83 y 86 de la figura del empenaje de cola se corresponden:", ops:["Al timón de profundidad y el vertical","Ninguna de las anteriores","A los trims"], r:1 },
        { id:"a85", p:"El timón vertical:", ops:["Está integrado dentro del estabilizador vertical","Está integrado dentro del empenaje de cola","No existe"], r:2 },
        { id:"a86", p:"A la parte móvil del estabilizador vertical se le conoce:", ops:["Timón de cola","Timón de dirección","Timón vertical"], r:1 },
        { id:"a87", p:"Un avión puede tener varios:", ops:["Pueden incluir dos o más estabilizadores","Dos o más estabilizadores verticales","Dos o más estabilizadores verticales y timones de profundidad"], r:1 },
        { id:"a88", p:"Los pozos están ubicados en:", ops:["El tren de aterrizaje","En el fuselaje","Ninguna de las anteriores"], r:1 },
        { id:"a89", p:"El tren de aterrizaje generalmente:", ops:["Se retrae al exterior","Se despliegan para rodar","Se retrae al interior de los pozos"], r:2 },
        { id:"a90", p:"El tren de aterrizaje se compone de:", ops:["Enclavamientos, amortiguadores neumáticos, frenos y ruedas","Enclavamientos, amortiguadores hidráulicos, llantas y neumáticos","Las dos anteriores son correctas"], r:1 },
        { id:"a91", p:"Durante el vuelo:", ops:["Los trenes se meten para ofrecer resistencia","Los trenes se retraen para ofrecer resistencia","Ninguna de las anteriores"], r:2 },
        { id:"a92", p:"Del texto se desprende que el tren de aterrizaje lleva frenos:", ops:["Según el temario, todos","Solo el principal","El conjunto en forma de triciclo"], r:1 },
        { id:"a93", p:"Solo los frenos frenan realmente al avión:", ops:["Sí; los frenos son muy potentes","Sí; exclusivamente los frenos son para eso","De ninguna forma"], r:2 },
        { id:"a94", p:"El principal problema que tienen los frenos:", ops:["Su gran desgaste","La diferencia de temperaturas del vuelo al paso de la frenada","El calor que se genera"], r:2 },
        { id:"a95", p:"Los neumáticos del avión:", ops:["Están formados de grandes capas","Llevan varias capas","Llevan dibujos y marcas en los laterales"], r:1 },
        { id:"a96", p:"Las ruedas de un avión llevan en su interior:", ops:["Oxígeno seco","Un gas inerte","Nitrógeno seco"], r:2 },
        { id:"a97", p:"¿Qué tipo de incendio se puede dar mayoritariamente en los frenos de un avión?", ops:["Tipo A","Tipo D","Tipo C"], r:1 },
        { id:"a98", p:"El calor disipado por los frenos directamente:", ops:["Es peligroso al estar debajo de los planos","Es peligroso por si afecta al fuselaje","Las dos anteriores"], r:0 },
        { id:"a99", p:"¿De qué disponen los neumáticos del avión?", ops:["De un gas inerte","De unos avisadores de temperatura","De válvulas de desinflado"], r:2 },
        { id:"a100", p:"Los frenos pueden estar fabricados:", ops:["De aleaciones","De composite y aleaciones","Ninguna de las anteriores"], r:2 },
      ]
    },
    {
      id: "aeropuertos",
      nombre: "Características de los Aeropuertos",
      icono: "🏢",
      preguntas: [
        { id:"ap1", p:"Desde un punto de vista operativo, es tradicional dividir el aeropuerto en dos grandes zonas de actividad:", ops:["Zona tierra y zona aire","Área de tierra y área aire","Lado tierra y lado aire"], r:2 },
        { id:"ap2", p:"'El área definida de tierra o agua, destinada, total o parcialmente, a la llegada, salida y movimiento en superficie de aeronaves.' ¿Quién da esta definición?", ops:["AENA","OACI","IATA"], r:1 },
        { id:"ap3", p:"Una de las cosas que comparten las dos zonas de actividad del aeropuerto es:", ops:["El cliente es el pasajero","Comparten en todo caso el concepto o palabra 'lado'","Comparten entre otros vestíbulos"], r:1 },
        { id:"ap4", p:"Entre las actividades operacionales del lado aire están:", ops:["Flujo de pasajeros","Salvamento y extinción de incendios","Medios para facilitar el flujo de pasajeros"], r:1 },
        { id:"ap5", p:"¿Qué se entiende por 'otras zonas' en un aeropuerto?", ops:["Las zonas no pavimentadas, donde se instalan las ayudas a la navegación","Camino perimetral, vías de acceso a instalaciones o al Área de Maniobras","Las dos son ciertas"], r:2 },
        { id:"ap6", p:"La plataforma estará dentro de:", ops:["Lado aire, área de maniobras","Lado tierra, área de movimiento","Lado aire, área de movimiento"], r:2 },
        { id:"ap7", p:"Los apartaderos de espera para los aviones se encuentran ubicados en:", ops:["Lado aire, área de maniobras","Lado tierra, área de movimiento","Lado aire, área de movimiento"], r:0 },
        { id:"ap8", p:"De entre las siguientes responsabilidades que tiene AENA en el Lado aire, NO se contempla:", ops:["Proporcionar infraestructuras","Asignar/contratar los handling","Vigilar el cumplimiento de la normativa de seguridad"], r:1 },
        { id:"ap9", p:"El área de movimiento está integrada por:", ops:["Área de movimiento y plataforma","Lado aire y plataforma","Área de maniobras y plataforma"], r:2 },
        { id:"ap10", p:"Empresas de suministro de combustible, personal de control del tráfico aéreo y personal de meteorología pertenecen a:", ops:["Personas que desempeñan sus funciones en lado tierra","Personas que desempeñan sus funciones en lado aire","Todas ellas son de AENA"], r:1 },
        { id:"ap11", p:"'Es un símbolo o grupo de símbolos expuestos en la superficie.' Esta definición pertenece a:", ops:["Señales","Letreros","Carteles"], r:0 },
        { id:"ap12", p:"Entre otras, los letreros:", ops:["Deben ser cuadrados","Pueden usarse los de instrucciones obligatorias","Visibles desde toda la pista"], r:1 },
        { id:"ap13", p:"Entre otras, los letreros:", ops:["Serán de texto negro y color rojo","Texto blanco y color negro","Color rojo y texto blanco"], r:2 },
        { id:"ap14", p:"¿Qué significa TWR si vemos un letrero que nos indica esas siglas?", ops:["Torre de control","Terminal del aeropuerto","Terminal lado oeste, derecha"], r:0 },
        { id:"ap15", p:"Los letreros se instalarán de modo que se podrán ver:", ops:["De lado al aproximarse al punto de rodaje o pista","De lado al aproximarse a la pista","De frente al aproximarse al punto de rodaje"], r:2 },
        { id:"ap16", p:"Las señales de información podrán colocarse para sustituir a:", ops:["Letreros de información como complemento","No serán usados","Se pondrán los dos preferiblemente"], r:0 },
        { id:"ap17", p:"De los siguientes, ¿cuál o cuáles NO se contemplan?", ops:["Balizas eliminatorias, balizas de freno y parada","Balizas de borde de pista, balizas de calle de rodaje","Balizas de borde de zona de parada, balizas de borde de pista sin pavimentar"], r:0 },
        { id:"ap18", p:"¿Dónde NO nos encontraremos una baliza?", ops:["Área de movimiento","Lado tierra","Área de maniobras o plataforma"], r:1 },
        { id:"ap19", p:"'Son objetos expuestos sobre el nivel del terreno para indicar un obstáculo o trazar un límite.' Esta definición pertenece a:", ops:["Barreta","Señal o línea","Balizas"], r:2 },
        { id:"ap20", p:"¿Qué elemento dará destellos de color blanco y verde alternados o destellos blancos solamente?", ops:["La Barreta","Faro de aeródromo","Las balizas"], r:1 },
        { id:"ap21", p:"Aquella zona del aeródromo que se usa para el despegue, el aterrizaje y el rodaje de aeronaves, excluyendo la Plataforma, se conoce como:", ops:["Pista","Lado aire","Área de maniobras"], r:2 },
        { id:"ap22", p:"El acceso y permanencia de vehículos y personas en el Área de Maniobras requiere la autorización expresa de:", ops:["La dirección del aeropuerto","El señalero","La torre de control"], r:2 },
        { id:"ap23", p:"Esta autorización (acceso y permanencia en el área de maniobras) se consigue:", ops:["Mediante formulario a la torre","Por vía radiocomunicación","Se consigue también por teléfono o vía radio"], r:1 },
        { id:"ap24", p:"'Un área rectangular definida dentro del aeródromo para el aterrizaje y despegue de las aeronaves.' Esta definición pertenece a:", ops:["Área de maniobras","Pista","Área de movimiento"], r:1 },
        { id:"ap25", p:"¿Qué es un ARP y dónde se sitúa?", ops:["Es un punto aeronáutico de posición; estará a unas millas de la torre de control","Es un punto de referencia del aeródromo y estará dentro de la pista","Es un punto de referencia del aeródromo y estará dentro del área de maniobras"], r:2 },
        { id:"ap26", p:"De las siguientes, NO es una característica principal que configura la pista:", ops:["Longitud, Anchura","Longitud, anchura y dirección","Orientación"], r:1 },
        { id:"ap27", p:"En un aeropuerto por encima del nivel del mar, un Boeing 747-400 con el máximo peso al despegue:", ops:["Necesitará menos distancia de pista para el despegue","Necesitará más distancia de pista para el despegue","Necesitará más distancia de pista para el aterrizaje"], r:1 },
        { id:"ap28", p:"¿Qué nos condicionará a la hora de diseñar la pista de despegue en el aeropuerto?", ops:["La distribución de los vientos dominantes en la zona","La distribución del terreno y el mar cercano","Sobre todo la orografía, por encima de los vientos"], r:0 },
        { id:"ap29", p:"El pavimento debe tener resistencia suficiente para soportar el tránsito de las aeronaves y disponer de adecuadas características de rozamiento cuando:", ops:["La pista esté mojada","La pista esté a temperaturas extremas","Las dos son ciertas"], r:0 },
        { id:"ap30", p:"En cuanto a los márgenes de la pista, NO podemos afirmar que:", ops:["Bordean el pavimento a ambos lados de la pista","Soportarán el peso de los vehículos que operen","Todos los tipos de pista tendrán márgenes"], r:2 },
        { id:"ap31", p:"'Reducir el riesgo de daños de las aeronaves que se salgan de la pista.' Es una función de:", ops:["Margen de pista","Franja de pista","Arcén de pista"], r:2 },
        { id:"ap32", p:"Las pistas pueden clasificarse en función de:", ops:["La categoría del aeropuerto","La zona donde esté el aeropuerto","Las ayudas instrumentales de que dispongan"], r:2 },
        { id:"ap33", p:"Las pistas del tipo Categoría II y de Categoría III dispondrán de:", ops:["Ayudas visuales","ILS, sistema de aterrizaje por instrumentos","Información sobre el rumbo"], r:1 },
        { id:"ap34", p:"Los colores de las señales de la pista serán de color:", ops:["Solo algunas","Todas","Todas menos las de zona de parada son amarillas"], r:1 },
        { id:"ap35", p:"¿Qué le falta a este dibujo de izquierdas a derechas? (los cuadros en blanco son: tras EXTREMO DE PISTA, y tras BORDE DE PISTA)", ops:["Punto de visada y umbral desplazado","Zona de parada y umbral de visada","Umbral desplazado y señal de punto de visada"], r:2 },
        { id:"ap36", p:"Se señaliza mediante fajas longitudinales y simétricas con respecto al eje de pista:", ops:["Señal de umbral","Borde de pista","Acceso a pista"], r:0 },
        { id:"ap37", p:"Una pista tiene dos designadores, situados:", ops:["En los extremos los dos","Uno en cada extremo","El designador se sitúa en el centro"], r:1 },
        { id:"ap38", p:"Refiriéndonos a los umbrales en el caso de la pista, NO se contempla como caso particular:", ops:["Umbral desplazado temporalmente","Umbral desplazado permanentemente","Umbral desplazado localmente"], r:2 },
        { id:"ap39", p:"La señalización del eje de pista será de forma:", ops:["Línea continua blanca","Línea discontinua amarilla; la anchura de la línea será variable","Línea discontinua blanca"], r:2 },
        { id:"ap40", p:"Las luces del borde de pista se emplazarán a lo largo de la pista, en dos filas equidistantes del eje, espaciadas a intervalos uniformes. Son de color:", ops:["Blanco","Rojo","Blanco, excepto cuando la pista tenga el umbral desplazado"], r:2 },
        { id:"ap41", p:"Indica la que corresponde respecto a la longitud de la zona de toma de contacto:", ops:["Depende de la distancia de aterrizaje disponible o la distancia entre umbrales","Depende de la distancia de despegue física o la distancia entre umbrales","Depende de la distancia de despegue disponible o la distancia entre umbrales"], r:0 },
        { id:"ap42", p:"Las señales del punto de visada son:", ops:["Blancas y cuadradas simétricas al borde de pista","Pares de señales rectangulares simétricas al eje de pista","Rectangulares y de color blanco simétricas al eje de pista"], r:2 },
        { id:"ap43", p:"Las vías que permiten el rodaje de las aeronaves y el enlace entre una y otra parte del aeropuerto se llaman:", ops:["Calles de acceso a pista","Acceso al aeródromo","Calles de rodaje"], r:2 },
        { id:"ap44", p:"Las principales características físicas de las calles de rodaje son: indica la INCORRECTA:", ops:["Resistencia del pavimento adecuada al tráfico que ha de soportar","Pendientes transversales que permitan suficiente distancia visible","Pendientes transversales adecuadas para impedir la acumulación del agua"], r:1 },
        { id:"ap45", p:"'El área concreta en un aeródromo terrestre, destinada a dar cabida a las aeronaves, para los fines de embarque o desembarque de pasajeros, correo o carga, abastecimiento de combustible, estacionamiento o mantenimiento.' Esta definición corresponde a:", ops:["Terminal","Finger o escaleras de embarque","Plataforma"], r:2 },
        { id:"ap46", p:"La Plataforma está determinada por la línea de borde de Plataforma y señalizada por:", ops:["Una línea blanca continua","Dos líneas amarillas","Dos líneas discontinuas blancas"], r:1 },
        { id:"ap47", p:"'ERA' dentro del contexto de estacionamiento de aeronaves es:", ops:["Los equipos de respiración de bomberos de aeropuertos","Área de retención de equipos","Las dos son falsas"], r:1 },
        { id:"ap48", p:"NPA estas siglas significan:", ops:["Señal de prohibido circular","Señal de prohibido aparcar de área","Señal de prohibido pasar por esa área"], r:1 },
        { id:"ap49", p:"ESL significa:", ops:["Línea de estacionamiento de equipos","Línea de espera de equipos","Línea de seguridad de equipos"], r:1 },
        { id:"ap50", p:"'Proporciona al piloto información relativa al rumbo y pendiente de descenso correcto a la pista que, si se siguen, harán que la aeronave realice un descenso y, en su caso, toma, con precisión y seguridad y sin necesidad de que el piloto recurra a referencias visuales exteriores.' Se denomina:", ops:["LLZ","ILS","GP"], r:1 },
      ]
    },
    {
      id: "comunicaciones",
      nombre: "Comunicaciones",
      icono: "📻",
      preguntas: [
        { id:"c1", p:"El comunicarse significa:", ops:["Hablar, llamar","Enviar un mensaje y que se comprenda","Hablar o gesticular"], r:1 },
        { id:"c2", p:"Podemos definir la comunicación como:", ops:["La transmisión codificada en forma de señales, palabras, sonidos entre 2 personas","La transmisión, emisión y recepción codificada en forma de señales, palabras, sonidos, que se va a producir entre personas","La emisión y recepción codificada en forma de señales, palabras, sonidos, que se va a producir entre personas"], r:1 },
        { id:"c3", p:"La realización de la transmisión de información se podrá realizar de forma (señala la INCORRECTA):", ops:["Electromagnéticos","Radioeléctrica, hilo","Electromecánicos"], r:2 },
        { id:"c4", p:"En los aeropuertos se utilizan distintos tipos de medios de comunicación (¿cuál no procede según temario?):", ops:["Radio","Teléfono","Informática"], r:2 },
        { id:"c5", p:"Ejemplo de los distintos equipos que pueden utilizarse en un aeropuerto (marca la correcta según tabla):", ops:["Del personal de operaciones a TWR, uso del monitor televisión","Del personal del SEIS a TWR, uso de la pantalla ordenador","De TWR a personal de operaciones, uso del teléfono"], r:2 },
        { id:"c6", p:"En el caso de los bomberos, ¿cómo se realizará la comunicación de Repostaje con pasaje a bordo? (De los bomberos a operaciones):", ops:["A través de la radio","Por teléfono se confirmará","Mediante telemático"], r:0 },
        { id:"c7", p:"Las comunicaciones aeronáuticas radiotelefónicas se han de realizar:", ops:["En inglés solamente","Se podrán realizar en castellano","En cualquier idioma del país"], r:1 },
        { id:"c8", p:"En dichas comunicaciones intervienen unos códigos propios (entre los que NO están):", ops:["Alfabeto (OACI)","Transmisión de números","Idioma aeronáutico"], r:2 },
        { id:"c9", p:"¿Cuándo se usa la fraseología en el ámbito de un aeropuerto?", ops:["Cuando no es necesario deletrear nombres propios, abreviaturas de servicio y todas aquellas palabras cuya comprensión sería dudosa de otro modo","Cuando es necesario deletrear nombres propios, todas aquellas palabras cuya comprensión sería dudosa de otro modo","Cuando es necesario deletrear nombres propios, abreviaturas de servicio y no todas aquellas palabras cuya comprensión sería dudosa de otro modo"], r:1 },
        { id:"c10", p:"'D' se nombra vía radio como:", ops:["Dédalo","Delta","De"], r:1 },
        { id:"c11", p:"'W' se nombra vía radio como:", ops:["Wilson","Wine","Whiski"], r:2 },
        { id:"c12", p:"UNIFORM es como se nombra la letra:", ops:["F","U","N"], r:1 },
        { id:"c13", p:"¿Cómo realizaremos la transmisión de números?", ops:["Se pronunciará todo junto","Se pronunciará cada dígito por separado","Uno a uno"], r:1 },
        { id:"c14", p:"Por ejemplo, para decir el número 100:", ops:["Se dirá CIEN","Se diría uno, cero, cero","Se diría un uno y dos ceros"], r:0 },
        { id:"c15", p:"Por ejemplo, para decir el número 10.000:", ops:["Se dirá diez cientos","Se diría uno, cero, cero, cero, cero","Se diría diez mil"], r:2 },
        { id:"c16", p:"Para transmitir en inglés aeronáutico '9' se diría:", ops:["Nime","Nind","Nine"], r:2 },
        { id:"c17", p:"En el contexto de la fraseología aeronáutica el término 'Cleared' significa:", ops:["Permiso para adelante","Permiso para rodar","Permiso para seguir en las condiciones determinadas"], r:2 },
        { id:"c18", p:"En el contexto de la fraseología aeronáutica el término 'aprobado' significa:", ops:["Permiso para seguir adelante","Autorización concedida","Permiso para seguir en las condiciones determinadas"], r:1 },
        { id:"c19", p:"Para indicar 'he terminado mi transmisión':", ops:["The end","Cancel","Over"], r:2 },
        { id:"c20", p:"¿Cómo nos indicaría la torre que prosigamos nuestro mensaje?", ops:["Go on","Continus","Go ahead"], r:2 },
        { id:"c21", p:"¿Qué necesitamos en el contexto de una comunicación para que puedan realizarse de forma correcta?", ops:["Una actitud de atención permanente","Hablar correctamente inglés","Conocer el alfabeto aeronáutico"], r:0 },
        { id:"c22", p:"De los elementos que se nombran de comunicación, ¿cuál NO corresponde a los listados?", ops:["Medio","Confirmación","Walkie"], r:2 },
        { id:"c23", p:"¿Quién debe ser 'consciente' de que el receptor puede recibir de forma diferente lo que quiere transmitir?", ops:["El receptor","El medio","El emisor"], r:2 },
        { id:"c24", p:"Antes de emitir un mensaje, toda persona ha de:", ops:["Escuchar","Sintonizar","Probar y identificarse"], r:0 },
        { id:"c25", p:"Al realizar una llamada sin recibir contestación, se recomienda dejar un tiempo antes de insistir, un tiempo de:", ops:["Un par de segundos","Aprox. 10 segundos","Unos 4 segundos"], r:1 },
        { id:"c26", p:"En la transmisión inicial que precede a una comunicación deben tenerse en cuenta dos cosas importantes: NO corresponde:", ops:["Para comenzar hay que usar el distintivo de llamada completo","A continuación no será necesario indicar su propio distintivo completo de llamada","A continuación será necesario indicar su propio distintivo completo de llamada"], r:1 },
        { id:"c27", p:"Dentro de las transmisiones 'objeto', el personal indicará en orden:", ops:["Sus intenciones y posición","Su posición e intenciones","Su identificativo e intenciones"], r:1 },
        { id:"c28", p:"En el desarrollo de la comunicación:", ops:["Estas serán breves y colacionadas, según marca el reglamento de circulación aéreo","Serán corroboradas y altas para ser oídas","Serán confirmadas y según marca el reglamento de circulación de tráfico"], r:0 },
        { id:"c29", p:"La TWR nos podrá indicar en cualquier momento que:", ops:["Dejemos la pista libre","Abandonemos el parque","Salgamos del aeropuerto por accidente"], r:0 },
        { id:"c30", p:"Para indicar el fin de una comunicación, ¿cómo lo diremos?", ops:["End","Corto","Terminado"], r:2 },
        { id:"c31", p:"Circulando con un vehículo del SEIS con intenciones de cruzar la pista:", ops:["Tendremos prioridad sobre los demás usuarios","No entraremos hasta que no tengamos permiso para cruzar","Poniendo las luces de prioridad y comunicando a la TWR será suficiente"], r:1 },
        { id:"c32", p:"No se puede utilizar la palabra __________ para comunicaciones con los vehículos, ya que este término solo se utiliza con las aeronaves.", ops:["Despegar","Cruzar","Autorizar"], r:2 },
        { id:"c33", p:"¿Cuándo notificaremos y cómo comunicaremos que hemos dejado de usar la pista?", ops:["Cuando ya estemos fuera de ella o rebasado totalmente... 'abandonamos pista TWR'","Cuando estemos ya fuera de la misma (a una distancia 70m borde)... 'pista libre'","Cuando estemos ya en las proximidades del siguiente punto de espera... 'pista abandonada'"], r:1 },
        { id:"c34", p:"Cuando una estación recibe una llamada inicial dirigida a ella, ¿cómo procederá?", ops:["Primero ha de asegurarse de la procedencia e identificación del emisor","Primero repetirá su propio indicativo a quien le llama por la radio","Lo más importante es entender intenciones, sin necesidad de recabar más información"], r:0 },
        { id:"c35", p:"A la hora de intercambiar mensajes se usa la palabra:", ops:["Prosiga","Cambio","Adelante"], r:2 },
        { id:"c36", p:"Para poder comunicar que se ha cometido un error en la transmisión de un mensaje, se utiliza la palabra:", ops:["Repito","Error repito","Corrección"], r:2 },
        { id:"c37", p:"En terminología aeronáutica, ¿cómo identificamos al puesto donde se estaciona una aeronave?", ops:["Parking","Stand","Taxi"], r:1 },
        { id:"c38", p:"A la condición que afecta a alguna persona a bordo o que esté al alcance de la vista, pero que no exige ayuda inmediata:", ops:["Peligro","Emergencia","Urgencia"], r:2 },
        { id:"c39", p:"'Tráfico de socorro', ¿cómo lo designaremos en un mensaje?", ops:["Pan Pan","Medical","Mayday"], r:2 },
        { id:"c40", p:"A la condición de requerir ayuda inmediata, la designaremos como:", ops:["Peligro","Emergencia","Urgencia"], r:0 },
        { id:"c41", p:"La frecuencia usada normalmente:", ops:["121,5 MHz","130,7 MHz","128 MHz"], r:0 },
        { id:"c42", p:"¿Quién podrá imponer la condición de silencio?", ops:["Solo la torre","La estación en peligro","Solo la estación que controle el tráfico de socorro"], r:1 },
        { id:"c43", p:"¿Cómo se impondrá la condición de silencio en una situación de socorro?", ops:["Pan pan","Stop transmitting","Las dos son falsas"], r:1 },
        { id:"c44", p:"Señala la INCORRECTA del siguiente supuesto sobre las comunicaciones de socorro:", ops:["Todo el tráfico de socorro haya sido transferido a otras frecuencias","Tenga ella misma que prestar ayuda","No tenga permiso de la estación que controle las comunicaciones"], r:2 },
        { id:"c45", p:"'DISTRESS TRAFFIC ENDED' estas indicaciones se dan cuando:", ops:["Termina la situación de emergencia y actuación bomberos","Se termina la condición de silencio","Se inicia la situación de comunicaciones de socorro del tráfico"], r:1 },
        { id:"c46", p:"¿Quién podrá anular mediante mensaje la condición de peligro de una aeronave?", ops:["El jefe de los bomberos entre otros","La estación que controle las comunicaciones","La torre siempre"], r:1 },
        { id:"c47", p:"En toda transmisión de prueba, ¿cuál NO corresponde a los pasos a tener en cuenta?", ops:["Identificación del usuario","Identificación del vehículo que llama","Identificación de la frecuencia que se usa"], r:0 },
        { id:"c48", p:"En la prueba se deberá utilizar una escala de legibilidad de los mensajes. ¿Cuántos son?", ops:["4","3","5"], r:1 },
        { id:"c49", p:"La prueba con una escala de legibilidad de 2 significa que:", ops:["Bien legible","Legible de vez en cuando","Legible con dificultad"], r:1 },
        { id:"c50", p:"¿Qué nivel de legibilidad es el mínimo para poder entrar en el área de maniobras?", ops:["4","3","2"], r:0 },
        { id:"c51", p:"¿Qué tipo de mensaje tendrá prioridad sobre el resto?", ops:["Todos los de ATC","Los de ATC excepto los de socorro y urgencia","La prioridad será de los bomberos"], r:1 },
        { id:"c52", p:"Entre las consideraciones a tener en cuenta, la propia forma de hablar se destaca:", ops:["Vocalización, claridad y ritmo","Claridad, ritmo y pronunciación","Calidad, ritmo y tono"], r:0 },
        { id:"c53", p:"¿De qué nos aseguraremos ante una situación estresante en una conversación radiotelefónica?", ops:["No dejar el pulsador bloqueado","Dejar bloqueado el pulsador","No soltar el pulsador después de transmitir el mensaje"], r:0 },
        { id:"c54", p:"El equipo de transmisiones comprende la banda:", ops:["De 118 a 135 MHz","De 120 a 130 MHz","De 112 a 123 MHz"], r:0 },
        { id:"c55", p:"En cuanto a la banda modulada FM, podemos decir que:", ops:["Comienza donde finaliza la aérea","Finaliza donde comienza la aérea","Es independiente; es AM"], r:1 },
        { id:"c56", p:"En caso de fallo de las comunicaciones radiotelefónicas, los destellos rojos significan:", ops:["Parar","Apartarse del área de aterrizaje","Desalojar el área de maniobras"], r:1 },
        { id:"c57", p:"¿Quién será el encargado de realizar las señales luminosas?", ops:["CEOPS","La Torre","Tanto la torre como el jefe de bomberos o cualquier usuario del aeropuerto"], r:1 },
        { id:"c58", p:"En condiciones de emergencia, en pistas o calles de rodaje equipadas con sistemas de iluminación, el destello de luces de pista significa:", ops:["Permanecer en la pista a que den indicaciones","Conectar la emisora por canal de torre","Desalojar la pista o calle de rodaje"], r:2 },
        { id:"c59", p:"¿Cómo realizaríamos la señal de acelerar bomba del camión?", ops:["Elevando los dos brazos paralelos al cuerpo","Haciendo ok con el pulgar de la mano derecha al bombero bomba","Subiendo el brazo izquierdo por encima del cuerpo con un dedo apuntando arriba"], r:2 },
        { id:"c60", p:"¿Cómo le indicaremos al piloto que pare los motores para realizar la evacuación?", ops:["Brazos detrás de la cabeza cruzados en las muñecas","Brazos frente a la cabeza cruzados en las muñecas","Manos frente a la cabeza cruzadas en las muñecas"], r:2 },
      ]
    },
    {
      id: "urgencias",
      nombre: "Urgencias Médicas",
      icono: "🚑",
      preguntas: [
        { id:"u1", p:"¿Dónde se integra y describe la clasificación de urgencias y cuidados médicos?", ops:["Parte 1 DOC 9137","Parte 7 DOC 9137","Parte 1 DOC 9173"], r:1 },
        { id:"u2", p:"Según se identifica en la documentación cap. 9, referente a las necesidades a atender inmediatamente a las personas lesionadas:", ops:["La atención médica será inmediata","Será proporcionada después de una primera extinción","Ha de ser proporcionada después del triaje"], r:0 },
        { id:"u3", p:"Después de un accidente, ¿cómo procederemos? (indica la versión más evidente con lo citado en el Cap. 9):", ops:["Los supervivientes deberán someterse a una selección y clasificación de sus lesiones","Los heridos se seleccionarán dependiendo del lugar que ocupen en el avión","Los heridos han de abandonar lo antes posible el lugar dirigiéndose al sitio apartado"], r:0 },
        { id:"u4", p:"La tarea de seleccionar a los heridos se conoce como:", ops:["Clasificación de emergencias","Clasificación de urgencias","Clasificación médica"], r:0 },
        { id:"u5", p:"El motivo principal de esta clasificación de los heridos se realiza:", ops:["Se realiza para informar de lo que tenemos prioritariamente y evacuar a la terminal","Ser prontamente evacuados hacia las instalaciones médicas adecuadas","Para poder organizar mejor las emergencias médicas"], r:1 },
        { id:"u6", p:"¿Qué determinará la clasificación y selección de víctimas?", ops:["Un orden de prioridad hospitalaria","Un orden de prioridad tratamiento y transporte","Un orden de prioridad del tratamiento in situ"], r:1 },
        { id:"u7", p:"¿Cuántas categorías se identifican o clasifican las urgencias?", ops:["2","4","5"], r:1 },
        { id:"u8", p:"La categoría V (prioridad) que clasifica:", ops:["Ninguna","Fallecidos","Carbonizados"], r:0 },
        { id:"u9", p:"La prioridad 1 nos determinará:", ops:["Cuidados demorados","Cuidados prioritarios","Cuidados inmediatos"], r:2 },
        { id:"u10", p:"Los cuidados de menor importancia se categorizan en:", ops:["Prioridad III","Prioridad II","Prioridad IV"], r:0 },
        { id:"u11", p:"La categoría de clasificación de víctimas determinada por prioridad II es:", ops:["Cuidados paliativos","Cuidados demorados","Cuidados de menor importancia"], r:1 },
        { id:"u12", p:"¿Quién ha de iniciar la clasificación de urgencias?", ops:["El primero que llegue al lugar del siniestro","El médico o jefe de dotación siempre","La primera persona con conocimientos médicos en el lugar"], r:2 },
        { id:"u13", p:"Cuando el aeropuerto proporcione un médico en el lugar del siniestro, la persona que está realizando inicialmente el proceso de clasificación:", ops:["Continuará con el proceso independientemente de que esté el médico","Será sustituido por el médico","Continuará haciendo su labor con el médico"], r:1 },
        { id:"u14", p:"Con respecto a la cuestión anterior, indica la correcta (médico):", ops:["Siempre será un médico","No siempre ha de ser un médico","No será designada por el aeropuerto; vendrá del 112 local más cercano"], r:1 },
        { id:"u15", p:"¿Qué dos zonas se designan después de un accidente con víctimas?", ops:["Zona de clasificación y zona de atención primaria","Zona de espera cuidados apropiados y zona de urgencias médicas","Zona de espera cuidados apropiados y zona de clasificación"], r:2 },
        { id:"u16", p:"¿Dónde se estipula que se realice la estabilización de las lesiones a las víctimas de un accidente aéreo?", ops:["Zona de accidente","Zona de estabilización urgencias","Zona de espera"], r:2 },
        { id:"u17", p:"Si representamos las prioridades a atender de forma piramidal, en su cúspide estarían:", ops:["Víctimas de prioridad I","Víctimas de prioridad que muestran gritos y que se quejan","Víctimas de prioridad IV"], r:0 },
        { id:"u18", p:"¿Cómo sería una actuación lo más eficaz posible en el ámbito de las urgencias en un accidente aéreo?", ops:["Realizar la clasificación de urgencias en lugar apartado del accidente","La clasificación la realizaría en el propio lugar del accidente","Bajo ningún concepto realizarla en el propio lugar accidente"], r:1 },
        { id:"u19", p:"Cuando como bomberos llegamos al lugar del accidente aéreo con víctimas, una de las prioridades será:", ops:["Asegurar la zona y dejar a las víctimas junto al avión","Separar a las víctimas de las operaciones de extinción, lugar seguro","Alejar a las víctimas lo más posible del lugar del siniestro"], r:1 },
        { id:"u20", p:"¿Cómo procederemos en la clasificación de urgencia para poder identificar los lesionados y los tipos?", ops:["Mediante un código de marcado","Mediante un etiquetado identificativo","Mediante unas señales identificativas"], r:1 },
        { id:"u21", p:"¿Quién atenderá inicialmente a las víctimas a la llegada al siniestro, después de la llamada de alarma?", ops:["Los bomberos del aeropuerto","El personal designado para la urgencia en la terminal, médico o ATS","La persona que considere más apropiada la dirección del aeropuerto"], r:0 },
        { id:"u22", p:"La identificación se realizará a través de unas:", ops:["Tarjetas normalizadas","Tarjetas codificadas","Etiquetas con señales"], r:0 },
        { id:"u23", p:"¿Qué funciones cumplen las etiquetas?", ops:["Ayudan a acelerar el tratamiento de multitud de víctimas y facilitar la evacuación","Identifican estadísticamente las víctimas para su transporte","Ninguna función"], r:0 },
        { id:"u24", p:"Las etiquetas normalizadas se deberán disponer:", ops:["Que sean grandes y claras con colores llamativos","Que sean grandes, usadas en condiciones adversas y permeables","Que sean impermeables, se puedan usar en condiciones meteorológicas adversas"], r:2 },
        { id:"u25", p:"Según el temario, ¿en qué lugar de la documentación de OACI se muestra un claro ejemplo de los números y símbolos representativos de las etiquetas?", ops:["Capítulo 8","Anexo 8","Apéndice 8"], r:2 },
        { id:"u26", p:"De las siguientes clasificaciones, ¿cuál es la correcta?", ops:["Roja, amarilla, azul, negra","Verde, azul, negra, roja","Ninguna de las dos anteriores"], r:2 },
        { id:"u27", p:"De las siguientes, ¿cuál de estas está bien?", ops:["Número romano I, símbolo tortuga","Número romano II, símbolo ambulancia","Número romano III, símbolo ambulancia"], r:2 },
        { id:"u28", p:"La etiqueta con símbolo de tortuga nos muestra:", ops:["Que la evacuación es inminente; no se ha de esperar","Cuidados demorados","Cuidados menores"], r:1 },
        { id:"u29", p:"¿Cuál sería la etiqueta que pondríamos en último lugar, una vez intentado todo, por esa víctima fallecida?", ops:["La prioridad I","La negra","La de prioridad V"], r:1 },
        { id:"u30", p:"¿Cómo realizaríamos la clasificación si no tenemos etiquetas?", ops:["Con mucho cuidado con números 1,2,3,4,5","Con letras: negro, azul, etc.","Con números romanos"], r:2 },
        { id:"u31", p:"Señala la INCORRECTA de las siguientes situaciones:", ops:["Cuando no se disponga de marcadores, se podrá usar un lápiz labial para marcar víctimas","Se desaconseja el uso de plumas con punta de fieltro para marcar víctimas","Se podrá marcar a las víctimas en la frente"], r:1 },
        { id:"u32", p:"¿Cómo trataremos a los lesionados graves?", ops:["Trasladándolos de forma inmediata","Se deberá evitar su traslado inmediato antes de la estabilización","La estabilización de los lesionados graves se realizará fuera del lugar accidente"], r:1 },
        { id:"u33", p:"La planificación de emergencias en los aeropuertos, ¿dónde se trata?", ops:["En el Capítulo 9 de la parte 7","En la parte 9 clasificación de urgencias y cuidados médicos","En la parte I salvamento y extinción de incendios"], r:0 },
        { id:"u34", p:"Una vez bien controlado el incendio, el personal disponible debe iniciar la tarea de:", ops:["Asegurar la zona con cintas y los propios vehículos","Clasificar, recoger y limpiar el mangaje, material en los vehículos","Estabilizar víctimas"], r:2 },
        { id:"u35", p:"De los siguientes materiales que se nombran en los principios aplicables médicos, NO se nombra:", ops:["Vendas, oxígeno, dispositivos de respiración artificial","Gasas, vendas, material de estabilización traumatismos","Compresas, equipo de estabilización por inhalación de humo"], r:1 },
        { id:"u36", p:"En la parte de principios aplicables a los cuidados médicos se cita que:", ops:["Se dispondrán de al menos un equipo por vehículo de oxígeno para el SEIS","No se dispondrá de equipo de oxígeno para SEIS; con los ERAS y su reservas será suficiente","Se dispondrán de suficiente cantidad de oxígeno para ser usado por el SEIS"], r:2 },
        { id:"u37", p:"Como medida de precaución debemos:", ops:["En zonas donde existan fugas de combustible o ropa impregnada usaremos el oxígeno","Debe usarse el oxígeno siempre que tengamos zonas de fugas de combustible","Las dos son falsas"], r:2 },
        { id:"u38", p:"El procedimiento de clasificación de urgencias y cuidado médico se ejercerá bajo el mando de:", ops:["El director de extinción y el jefe del PMA","La primera persona que llegue al lugar","El coordinador médico designado, una vez en el lugar"], r:2 },
        { id:"u39", p:"¿Quién tiene la responsabilidad en todos los aspectos médicos del incidente?", ops:["El jefe de operaciones","El director del aeropuerto","El coordinador médico designado"], r:2 },
        { id:"u40", p:"La función primaria de la figura responsable del procedimiento de clasificación de urgencias y cuidado médico será del tipo:", ops:["De atender a las víctimas directamente","Administrativa","Del tipo gestión"], r:1 },
        { id:"u41", p:"La figura responsable del procedimiento de clasificación de urgencias y cuidado médico depende en todo momento de:", ops:["No depende de nadie; si acaso informa al director","Tendrá que darle cuentas al jefe de dotación","Del jefe de operaciones"], r:2 },
        { id:"u42", p:"¿Qué tipo de indumentaria llevará el responsable de las acciones de clasificación urgencia y cuidado médico?", ops:["Casco azul y chaleco reflectante donde ponga J operaciones","Entre otras, un casco blanco como los bomberos","Entre otras, un chaleco reflectante que ponga en la espalda 'Médico'"], r:1 },
        { id:"u43", p:"De entre las nombradas, NO se contempla en las de prioridad I:", ops:["Lesiones por aplastamiento","Inhalación de humo","Vómitos"], r:2 },
        { id:"u44", p:"Una de las recomendaciones que se realizan como medidas es la de:", ops:["Administrar aire fresco a las víctimas","Dar algún líquido a los quemados","Colocar a las víctimas bajo cubierto antes de ser transportadas"], r:2 },
        { id:"u45", p:"De entre las nombradas, NO se contempla en las de prioridad II:", ops:["Fracturas abiertas","Fracturas cerradas extremidades","Quemaduras"], r:0 },
        { id:"u46", p:"Una de las cosas a tener en cuenta en las víctimas de prioridad III es que:", ops:["Son víctimas de extrema gravedad","Víctimas con pequeñas lesiones","Víctimas con lesiones importantes"], r:1 },
        { id:"u47", p:"Se nombran o designan unas zonas de emplazamiento de los lesionados (control de movimientos):", ops:["2 zonas","4 zonas","3 zonas"], r:1 },
        { id:"u48", p:"De las siguientes, señala la que NO corresponde de las zonas que se nombran como control de movimientos de lesionados:", ops:["Zona de recogida, zona de atención médica","Zona de transporte, zona de clasificación urgencias","Zona de cuidados, zona de recogida"], r:0 },
        { id:"u49", p:"¿Dónde tendrán que custodiar los bomberos a los heridos una vez asegurada la extinción del aeronave, en una primera actuación?", ops:["En la zona de clasificación","Zona de atención médica","Zona de recogida"], r:2 },
        { id:"u50", p:"¿Qué área o zona se nombra que deberá tener de 90 metros en contra viento?", ops:["En la zona de clasificación","Zona de atención médica","Zona de recogida"], r:0 },
        { id:"u51", p:"Inicialmente habrá una sola zona determinada, pero más tarde se deberán subdividir en varias subzonas. ¿En cuál?", ops:["En la zona de clasificación","Zona de atención médica","Zona de cuidados"], r:2 },
        { id:"u52", p:"¿Cuántas subzonas se determinarán?", ops:["2","3","4"], r:1 },
        { id:"u53", p:"Los colores de esas subzonas perfectamente identificadas corresponderán a:", ops:["Rojo cuidados inmediatos, amarillo cuidados demorados, azul cuidados menores","Rojo cuidados urgentes, amarillo cuidados demorados, blanco cuidados menores","Rojo cuidados inmediatos, amarillo cuidados demorados, verde cuidados menores"], r:2 },
        { id:"u54", p:"Además de códigos de colores, se podrán usar para los lesionados:", ops:["Conos de tráfico, banderines de color","Vallas separadoras","Vehículos de asistencia del aeropuerto"], r:0 },
        { id:"u55", p:"La recomendación que se da en las instalaciones móviles para las primeras prioridades es de:", ops:["Funcionando en menos de 60 minutos","Funcionando en menos de 30 minutos","Funcionando entre 30 minutos y una hora"], r:1 },
      ]
    },
    {
      id: "excarcelacion",
      nombre: "Equipos de Excarcelación",
      icono: "🔧",
      preguntas: [
        { id:"x1", p:"¿Qué ocurre cuando nos encontramos ante un elemento bajo presión o esfuerzo mecánico y tenemos la cizalla en funcionamiento?", ops:["No debemos usarla","Con cuidado podemos usarla","Trabajaremos en el mismo sentido que la tensión"], r:0 },
        { id:"x2", p:"¿Cómo estará la cizalla a la hora de cortar?", ops:["Paralela al material a cortar","Preferiblemente cortaremos por su extremo y perpendicular a la pieza","La cizalla ha de estar perpendicular al material a cortar"], r:2 },
        { id:"x3", p:"Una de las instrucciones de seguridad a seguir para el manejo de cilindros:", ops:["Que no estén sobre el pie de empuje","Podrá actuar con cargas oblicuas","Los cabezales solo deben estar en contacto con objetos a mover"], r:2 },
        { id:"x4", p:"Dentro de las instrucciones de seguridad de cilindros, NO se nombra de las siguientes:", ops:["Se podrán usar más de un tubo prolongador al mismo tiempo","Que los cabezales no se introducen en agujeros","Que no use más de un prolongador al mismo tiempo"], r:0 },
        { id:"x5", p:"En el manejo de la Bomba será importante: (indica la correcta)", ops:["Que la bomba tenga aceite entre otras","Que la bomba esté lo más cerca posible de edificios, a menos de 1m","Se podrá usar la bomba en espacios confinados"], r:0 },
        { id:"x6", p:"Las bombas podrán ser del tipo:", ops:["Eléctricas y a motor de explosión","Motor hidráulico y eléctricas","Las dos son ciertas"], r:0 },
        { id:"x7", p:"De entre las siguientes precauciones de uso para las mangueras, indica la INCORRECTA:", ops:["No utilice nunca mangueras sin los muelles antirretorno","Evite giros y retorcimientos en las mangueras","Evite la torsión en las mangueras"], r:0 },
        { id:"x8", p:"Las mangueras de los equipos se han de sustituir:", ops:["Dependiendo del uso y estado, cada 10 años","Con independencia del uso y estado, cada 10 años","Con independencia del uso y estado, cada 10 años o según daños visibles inmediatamente"], r:2 },
        { id:"x9", p:"Las piezas que han estado en contacto con ácidos o líquidos agresivos:", ops:["Se han de limpiar con disolvente y volver a pintarlas","Se aclararán con agua solamente","Solo si son de plástico se pintarán"], r:1 },
        { id:"x10", p:"El grupo de presión se configura por:", ops:["Un motor eléctrico de 4 tiempos","Motor de explosión de 2 tiempos","Las dos son falsas"], r:2 },
        { id:"x11", p:"Dentro del grupo de presión, NO se citan características como:", ops:["Presión trabajo 360b","Combustible gasolina","Válvula comentadora"], r:0 },
        { id:"x12", p:"De los siguientes, ¿cuál NO se cita como nivel de los grupos de presión?", ops:["Nivel aceite","Nivel del agua refrigerante","Nivel del combustible"], r:1 },
        { id:"x13", p:"¿Cómo se arranca el grupo de presión?", ops:["Dando al botón de arranque grupo","Tirando del cordón o lanzadera","Dando pulsaciones a la bomba"], r:1 },
        { id:"x14", p:"Según se ve en la foto, se puede identificar como:", ops:["Grupo de excarcelación","Grupo de presión","Grupo de excarcelación"], r:1 },
        { id:"x15", p:"Antes de arrancar el grupo:", ops:["No se han de conectar las mangueras","Se conectarán las herramientas","Se conectarán las mangueras"], r:2 },
        { id:"x16", p:"¿Qué tipo de conexiones se usan en los equipos de excarcelación?", ops:["Conectores Barcelona","Conectores rápidos","Conectores de ranura"], r:1 },
        { id:"x17", p:"Si queremos cerrar la herramienta multiuso, ¿hacia dónde giraremos el mando?", ops:["Hacia la izquierda","A derechas","Hacia delante, al igual que la lanza"], r:1 },
        { id:"x18", p:"Una forma de comprobar el equipo después de mantenimiento o primera puesta en funcionamiento será:", ops:["Cortando directamente a media presión de grupo","Abrir el equipo varias veces","Abrir y cerrar el equipo varias veces para purgar"], r:2 },
        { id:"x19", p:"En el caso concreto de montar los ganchos y accesorios:", ops:["Los ganchos señalan a sentidos opuestos","Los ganchos han de señalar hacia abajo en distinta dirección","Los ganchos han de señalar hacia arriba"], r:2 },
        { id:"x20", p:"El equipo ha de estar almacenado:", ops:["En el camión","En lugar apropiado","En el almacén bien ordenado, según normativa de seguridad e higiene en el trabajo"], r:1 },
        { id:"x21", p:"Unas de las consideraciones a tener en cuenta a la hora de hacer un corte con la herramienta:", ops:["Las cuchillas estén bien afiladas y paralelas entre sí","Las cuchillas han de estar perfectamente en ángulo","Las cuchillas estén perpendiculares a la pieza a cortar"], r:2 },
        { id:"x22", p:"El nombre con que se conoce a la cuchilla de la herramienta es:", ops:["Blade","Blater","Perpendicular cuter"], r:0 },
        { id:"x23", p:"De las siguientes, indica la que NO corresponde:", ops:["Los cables no se podrán cortar","Se han de sujetar las piezas sueltas en sus extremos a ser posible","Las herramientas están diseñadas para cortar objetos de chapa"], r:0 },
        { id:"x24", p:"¿Qué tendremos que hacer antes de cortar?", ops:["Abrir el equipo","Cerrar el equipo","Colocar el equipo alrededor del objeto"], r:0 },
        { id:"x25", p:"Al final del corte, ¿qué operación deberíamos hacer?", ops:["Abrir el equipo","Cerrar el equipo","Quitar el equipo"], r:0 },
        { id:"x26", p:"¿Qué tendríamos que hacer para operar con el distribuidor con menos de dos herramientas?", ops:["Conectar las herramientas al 2 y 3","Conectar una manguera en el 2 y 3","Ninguna de las anteriores"], r:1 },
        { id:"x27", p:"Las posiciones numeradas como 2 y 3 son:", ops:["Puentes de conexión","Entradas","Salidas"], r:2 },
        { id:"x28", p:"Una vez realizadas todas las conexiones del equipo de excarcelación, ¿qué hacemos?", ops:["Mover la válvula a modo pressure","Arrancar el equipo","Poner en marcha la motobomba"], r:2 },
        { id:"x29", p:"La posición del distribuidor de descarga es conocida como:", ops:["Dumping","Pressure out","Dump"], r:2 },
        { id:"x30", p:"¿El gato hidráulico es una herramienta? (dentro del argot de los equipos de excarcelación):", ops:["Auxiliar","Básica","De presión"], r:0 },
        { id:"x31", p:"Si nos encontramos arena, polvo o suciedad en general en las mangueras:", ops:["Las limpiaremos con un trapo con disolvente","Solo con agua se han de limpiar","Se podrán limpiar con el mismo aceite o base de petróleo"], r:1 },
        { id:"x32", p:"Son equipos pensados para reducir la alta presión de los gases contenidos en el interior de una botella o canalizaciones, a la presión necesaria para el trabajo auxiliar. Esta descripción corresponde a:", ops:["Escoplo metálico","Escoplo neumático","ERA"], r:1 },
        { id:"x33", p:"De entre las partes más importantes que se nombran en los equipos de corte por aire, NO está la de:", ops:["Racor de entrada","Volante o palomilla","Válvula de seguridad"], r:0 },
        { id:"x34", p:"'Protege la zona de baja presión del manorreductor.' Esta descripción corresponde a:", ops:["Vastado o palomilla","Volante o palomilla","Válvula de seguridad"], r:2 },
        { id:"x35", p:"'Indica la presión o el caudal de salida.' Le corresponde esta función a:", ops:["Manómetro de alta","Rotámetro de baja presión","Válvula de seguridad"], r:1 },
        { id:"x36", p:"Indica la correcta de las siguientes expresiones:", ops:["'No utilizar nunca para limpiar los reductores, trapos que puedan llevar algún tipo de aceite o grasas. Los gases producen explosiones al entrar en contacto con estas sustancias.'","'No utilizar nunca para limpiar los manorreductores, trapos que puedan llevar algún tipo de gasolina o derivado petróleo. Los gases producen explosiones al entrar en contacto con estas sustancias.'","'No utilizar nunca para limpiar los manorreductores, trapos que puedan llevar algún tipo de aceite o grasas. Algunos gases producen explosiones al entrar en contacto con estas sustancias.'"], r:2 },
        { id:"x37", p:"Como medida de seguridad se ha de tener en cuenta (escoplo neumático):", ops:["Siempre abrir la botella de forma lenta","Operar el grifo en posición horizontal","Las dos son falsas"], r:0 },
        { id:"x38", p:"Como medida de seguridad NO se ha de tener en cuenta (escoplo neumático):", ops:["La apertura de la botella","La posición de la botella","La posición de la herramienta"], r:2 },
        { id:"x39", p:"Si detecta aceites o grasas en el manorreductor, debe ser limpiado por:", ops:["Por nosotros mismos","Por personal de la empresa suministradora","Por personal técnicamente cualificado"], r:2 },
      ]
    }
  ]
};

// Calcular total de preguntas
QUESTIONS_DB.total = QUESTIONS_DB.temas.reduce((sum, t) => sum + t.preguntas.length, 0);

// Crear índice global de todas las preguntas
QUESTIONS_DB.todas = QUESTIONS_DB.temas.flatMap(t => 
  t.preguntas.map(p => ({ ...p, tema: t.id, temaNombre: t.nombre, temaIcono: t.icono }))
);
